# This is a redirect rule for proxying API requests.
# It forwards any request from /api/* to your backend server.
[[redirects]]
  from = "/api/*"
  to = "https://cinema-booking.zapto.org/api/:splat"
  status = 200